name: uni_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  gap: ^3.0.1
  get: ^4.6.6
  lottie: ^3.1.2
  persistent_bottom_nav_bar: ^6.2.1
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/homeAssets/
